# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='des',
            field=models.TextField(max_length=20000),
        ),
    ]
